---
# --------------------------------

- name: "Include {{ ct_family }} tasks"
  include_tasks: setup-{{ ct_family }}.yml
  when:
  - ct_family == "debian" or ct_family == "redhat"
  tags: ["ct-certbot"]

- import_tasks: install-using-snap.yml
  when: certbot_install_method == "snap"
  become: true
  tags: ["ct-certbot"]

- name: "Install management script"
  ansible.builtin.copy:
    dest: /usr/local/bin/manage-letsencrypt.sh
    group: root
    mode: "0775"
    owner: root
    src: manage-letsencrypt.sh
  become: true
  tags: ["ct-certbot"]

- name: "Cron job for renewing certificates"
  ansible.builtin.cron:
    disabled: false
    hour: "2"
    job: "/usr/bin/certbot renew"
    minute: "25"
    name: "certbot_certificate_renewal"
    state: present
    user: root
    weekday: "6"  # Saturday
  become: true
  when: certbot_renew_using_cron
  tags: ["ct-certbot"]

# --------------------------------
...
