---
# --------------------------------

- name: "Include variables wrapper"
  ansible.builtin.include_tasks:
    file: variables.yml
  tags: [ct-certbot]

- name: "Disto/Family tasks (FF)"
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version.split('.')[0] }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"
  tags: [ct-certbot]

- name: "Use snap to install"
  ansible.builtin.import_tasks:
    file: install-using-snap.yml
  when: certbot_install_method == "snap"
  become: true
  tags: [ct-certbot]

- name: "Install management script"
  ansible.builtin.copy:
    dest: /usr/local/bin/manage-letsencrypt.sh
    group: root
    mode: "0775"
    owner: root
    src: manage-letsencrypt.sh
  become: true
  tags: [ct-certbot]

- name: "Render domains file"
  ansible.builtin.template:
    dest: /usr/local/etc/certbot-domains.txt
    group: root
    mode: "0644"
    owner: root
    src: certbot-domains.txt.j2
  become: true
  tags: [ct-certbot]

- name: "Cron job for renewing certificates"
  ansible.builtin.cron:
    disabled: false
    hour: "2"
    job: "/usr/bin/certbot renew"
    minute: "25"
    name: "certbot_certificate_renewal"
    state: present
    user: root
    weekday: "6"  # Saturday
  become: true
  when: certbot_renew_using_cron
  tags: [ct-certbot]

# --------------------------------
...
