---
# --------------------------------

- name: "RedHat : Enable CRB (aarch64,command)"  # no suitable module (Sept 2023)
  ansible.builtin.command:
    cmd: subscription-manager repos --enable codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms
  when:
  - ansible_architecture == "aarch64"
  - ansible_os_family == "RedHat"
  changed_when: false
  become: true
  tags: [ct-certbot, skip_ansible_lint]

- name: "RedHat : Enable EPEL (aarch64)"
  ansible.builtin.dnf:
    name: "{{ certbot_epel_url }}"
    state: present
  when:
  - ansible_architecture == "aarch64"
  - ansible_os_family == "RedHat"
  become: true
  tags: [ct-certbot]

- name: "RedHat : Install Pip packages (IECM)"
  ansible.builtin.pip:
    name: "{{ certbot_pkgs_pip }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: true
  tags: [ct-certbot]

- name: "RedHat : Install core packages"
  ansible.builtin.dnf:
    name: "{{ certbot_pkgs_core }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: true
  tags: [ct-certbot]

# --------------------------------
...
