---
name: linter
on: [push]
jobs:
  build:
    name: yamllint
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: run yammlint
      uses: karancode/yamllint-github-action@master
...
